### PR TITLE
feat: configure metrics and add simple example

### PR DESCRIPTION
**Pull request by vmihailenco**
I also took a chance to rename `install_simple` to `configure_opentelemetry` so it looks the same as in other distros.

### CODE REVIEW

**Comment by vmihailenco** [comment]
@bestgopher could you take a look please?

**Review by bestgopher — APPROVED** [review]
Nice!!

**Comment by bestgopher** [comment]
@vmihailenco You should publish a new version to crates.io

**Comment by vmihailenco** [comment]
@bestgopher I will, just want to make one more change...

**Comment by bestgopher** [comment]
That sounds greate.

**Pull request merged**
